[project]
name = "gap"
version = "0.1.0"
description = "court citation pour donnée le souffle qui manque a votre machin"
readme = "README.md"
authors = [
    { name = "Tosun-r", email = "moryax268@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
gap = "gap.cli:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
